### ISSUE TITLE
How to build flute from scratch?

### ISSUE THREAD

**Issue by LeiWang1999** [HanGuo97/flute#1]
Hi, all. I've noticed that the csrc of flute depends on cute, but it's not present in the submodules. Could you advise on which version of cutlass I should use, and would it be possible to provide the scripts to build Flute from scratch?

**Comment by HanGuo97** [comment]
Hi, the README was updated to include the CUTLASS version (`v3.4.1`), sorry for the confusion!

**Comment by LeiWang1999** [comment]
Thanks @HanGuo97 , amazing project and a great example of cute!

**Comment by HanGuo97** [comment]
Thanks for the kind words! Obviously, we benefited a lot from your project + helps as well --- highly appreciated!
